In [1]:
import pandas as pd
import seaborn as sns
import matplotlib
import matplotlib.pyplot as plt

In [2]:
df_child = pd.read_csv("1. Child opportunity index (LI and NYC).csv")

In [3]:
df_child.msaname15.value_counts()

New York-Newark-Jersey City, NY-NJ-PA Metro Area    2717
Name: msaname15, dtype: int64

In [4]:
df_child.describe()

,Unnamed: 0,geoid,year,in100,msaid15,countyfips,statefips,pop,z_ED_nat,z_HE_nat,...,r_SE_nat,r_COI_nat,r_ED_stt,r_HE_stt,r_SE_stt,r_COI_stt,r_ED_met,r_HE_met,r_SE_met,r_COI_met
count,2717.000000,2.717000e+03,2717.0,2717.0,2717.0,2717.000000,2717.0,2717.000000,2717.000000,2717.000000,...,2717.000000,2717.000000,2717.000000,2717.000000,2717.000000,2717.000000,2717.000000,2717.000000,2717.000000,2717.000000
mean,1359.000000,3.606083e+10,2015.0,1.0,35620.0,36060.733530,36.0,891.525580,0.012733,0.032804,...,39.938903,45.025764,53.018403,46.692676,46.961722,48.195436,48.274199,44.904674,45.484358,45.683474
std,784.474665,2.772107e+07,0.0,0.0,0.0,27.699996,0.0,537.881603,0.076406,0.024271,...,29.952293,30.002726,28.803707,26.345867,27.982861,27.958556,26.228847,25.072915,27.868924,26.689135
min,1.000000,3.600500e+10,2015.0,1.0,35620.0,36005.000000,36.0,0.000000,-0.169604,-0.106549,...,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000
25%,680.000000,3.604704e+10,2015.0,1.0,35620.0,36047.000000,36.0,499.000000,-0.046813,0.019589,...,14.000000,18.000000,27.000000,24.000000,24.000000,25.000000,27.000000,24.000000,23.000000,24.000000
50%,1359.000000,3.605952e+10,2015.0,1.0,35620.0,36059.000000,36.0,793.000000,0.011647,0.033858,...,33.000000,41.000000,56.000000,45.000000,43.000000,46.000000,48.000000,43.000000,42.000000,44.000000
75%,2038.000000,3.608106e+10,2015.0,1.0,35620.0,36081.000000,36.0,1175.000000,0.061100,0.048590,...,65.000000,72.000000,78.000000,67.000000,70.000000,72.000000,69.000000,64.000000,66.000000,66.000000
max,2717.000000,3.610320e+10,2015.0,1.0,35620.0,36103.000000,36.0,5422.000000,0.239422,0.112414,...,100.000000,100.000000,100.000000,100.000000,100.000000,100.000000,100.000000,100.000000,100.000000,100.000000

In [5]:
df_child.countyfips.value_counts()

36047    750
36081    646
36005    334
36103    322
36061    279
36059    278
36085    108
Name: countyfips, dtype: int64

In [6]:
df_child

,Unnamed: 0,geoid,year,in100,msaid15,msaname15,countyfips,statefips,stateusps,pop,...,r_SE_stt,r_COI_stt,c5_ED_met,c5_HE_met,c5_SE_met,c5_COI_met,r_ED_met,r_HE_met,r_SE_met,r_COI_met
0,1,36005000200,2015,1,35620,"New York-Newark-Jersey City, NY-NJ-PA Metro Area",36005,36,NY,1061,...,22,26,Low,Moderate,Low,Low,38,47,21,25
1,2,36005000400,2015,1,35620,"New York-Newark-Jersey City, NY-NJ-PA Metro Area",36005,36,NY,1225,...,27,33,Moderate,Moderate,Low,Low,48,55,26,33
2,3,36005001600,2015,1,35620,"New York-Newark-Jersey City, NY-NJ-PA Metro Area",36005,36,NY,1795,...,12,16,Low,Moderate,Very Low,Very Low,35,57,10,15
3,4,36005001900,2015,1,35620,"New York-Newark-Jersey City, NY-NJ-PA Metro Area",36005,36,NY,756,...,16,16,Very Low,Moderate,Very Low,Very Low,12,52,15,15
4,5,36005002000,2015,1,35620,"New York-Newark-Jersey City, NY-NJ-PA Metro Area",36005,36,NY,2866,...,1,2,Low,Moderate,Very Low,Very Low,26,45,1,2
5,6,36005002300,2015,1,35620,"New York-Newark-Jersey City, NY-NJ-PA Metro Area",36005,36,NY,1222,...,1,1,Low,Moderate,Very Low,Very Low,39,53,1,1
6,7,36005002500,2015,1,35620,"New York-Newark-Jersey City, NY-NJ-PA Metro Area",36005,36,NY,1784,...,4,4,Very Low,Very Low,Very Low,Very Low,7,16,4,3
7,8,36005002701,2015,1,35620,"New York-Newark-Jersey City, NY-NJ-PA Metro Area",36005,36,NY,1079,...,5,5,Very Low,Moderate,Very Low,Very Low,11,42,4,4
8,9,36005002702,2015,1,35620,"New York-Newark-Jersey City, NY-NJ-PA Metro Area",36005,36,NY,1492,...,2,2,Very Low,Low,Very Low,Very Low,3,33,2,1
9,10,36005002800,2015,1,35620,"New York-Newark-Jersey City, NY-NJ-PA Metro Area",36005,36,NY,1025,...,14,16,Low,Moderate,Very Low,Very Low,25,56,12,15
10,11,36005003100,2015,1,35620,"New York-Newark-Jersey City, NY-NJ-PA Metro Area",36005,36,NY,447,...,28,25,Very Low,Moderate,Low,Low,10,41,27,24
11,12,36005003300,2015,1,35620,"New York-Newark-Jersey City, NY-NJ-PA Metro Area",36005,36,NY,1312,...,1,1,Very Low,Moderate,Very Low,Very Low,5,41,1,1
12,13,36005003500,2015,1,35620,"New York-Newark-Jersey City, NY-NJ-PA Metro Area",36005,36,NY,1264,...,7,8,Very Low,Moderate,Very Low,Very Low,6,42,7,6
13,14,36005003700,2015,1,35620,"New York-Newark-Jersey City, NY-NJ-PA Metro Area",36005,36,NY,33,...,5,7,Very Low,Very High,Very Low,Very Low,5,90,5,6
14,15,36005003800,2015,1,35620,"New York-Newark-Jersey City, NY-NJ-PA Metro Area",36005,36,NY,343,...,16,19,Low,Low,Very Low,Very Low,33,33,15,18
15,16,36005003900,2015,1,35620,"New York-Newark-Jersey City, NY-NJ-PA Metro Area",36005,36,NY,1760,...,13,10,Very Low,Very Low,Very Low,Very Low,15,3,12,9
16,17,36005004001,2015,1,35620,"New York-Newark-Jersey City, NY-NJ-PA Metro Area",36005,36,NY,308,...,27,28,Low,Low,Low,Low,29,40,26,27
17,18,36005004100,2015,1,35620,"New York-Newark-Jersey City, NY-NJ-PA Metro Area",36005,36,NY,1833,...,1,1,Low,Low,Very Low,Very Low,24,28,1,1
18,19,36005004200,2015,1,35620,"New York-Newark-Jersey City, NY-NJ-PA Metro Area",36005,36,NY,1972,...,1,3,Low,Moderate,Very Low,Very Low,31,58,1,2
19,20,36005004300,2015,1,35620,"New York-Newark-Jersey City, NY-NJ-PA Metro Area",36005,36,NY,1700,...,5,4,Very Low,Low,Very Low,Very Low,2,30,4,3
20,21,36005004400,2015,1,35620,"New York-Newark-Jersey City, NY-NJ-PA Metro Area",36005,36,NY,1246,...,1,2,Very Low,Moderate,Very Low,Very Low,18,56,1,1
21,22,36005004600,2015,1,35620,"New York-Newark-Jersey City, NY-NJ-PA Metro Area",36005,36,NY,500,...,10,13,Very Low,High,Very Low,Very Low,18,78,9,11
22,23,36005004800,2015,1,35620,"New York-Newark-Jersey City, NY-NJ-PA Metro Area",36005,36,NY,1090,...,7,7,Very Low,Very Low,Very Low,Very Low,12,18,6,6
23,24,36005005001,2015,1,35620,"New York-Newark-Jersey City, NY-NJ-PA Metro Area",36005,36,NY,1595,...,5,5,Very Low,Low,Very Low,Very Low,13,23,4,4
24,25,36005005002,2015,1,35620,"New York-Newark-Jersey City, NY-NJ-PA Metro Area",36005,36,NY,1475,...,6,4,Very Low,Very Low,Very Low,Very Low,5,7,5,3
25,26,36005005100,2015,1,35620,"New York-Newark-Jersey City, NY-NJ-PA Metro Area",36005,36,NY,1855,...,6,14,Moderate,Moderate,Very Low,Very Low,55,59,6,12
26,27,36005005200,2015,1,35620,"New York-Newark-Jersey City, NY-NJ-PA Metro Area",36005,36,NY,663,...,6,6,Very Low,Moderate,Very Low,Very Low,5,45,5,5
27,28,36005005300,2015,1,35620,"New York-Newark-Jersey City, NY-NJ-PA Metro Area",36005,36,NY,1517,...,1,1,Very Low,Low,Very Low,Very Low,3,27,1,1
28,29,36005005400,2015,1,35620,"New York-Newark-Jersey City, NY-NJ-PA Metro Area",36005,36,NY,1675,...,8,6,Very Low,Very Low,Very Low,Very Low,2,9,7,5
29,30,36005005600,2015,1,35620,"New York-Newark-Jersey City, NY-NJ-PA Metro Area",36005,36,NY,702,...,7,6,Very Low,Very Low,Very Low,Very Low,10,13,6,5
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2687,2688,36103169800,2015,1,35620,"New York-Newark-Jersey City, NY-NJ-PA Metro Area",36103,36,NY,1189,...,33,31,Low,Very Low,Low,Low,30,16,32,30
2688,2689,36103169901,2015,1,35620,"New York-Newark-Jersey City, NY-NJ-PA Metro Area",36103,36,NY,1170,...,53,44,Low,Low,Moderate,Moderate,21,35,50,42
2689,2690,36103169902,2015,1,35620,"New York-Newark-Jersey City, NY-NJ-PA Metro Area",36103,36,NY,597,...,61,56,Low,Moderate,Moderate,Moderate,36,49,57,53
2690,2691,36103170001,2015,1,35620,"New York-Newark-Jersey City, NY-NJ-PA Metro Area",36103,36,NY,947,...,72,72,Moderate,High,High,High,58,69,69,66
2691,2692,36103170002,2015,1,35620,"New York-Newark-Jersey City, NY-NJ-PA Metro Area",36103,36,NY,621,...,72,73,High,High,High,High,67,64,69,67
2692,2693,36103170101,2015,1,35620,"New York-Newark-Jersey City, NY-NJ-PA Metro Area",36103,36,NY,396,...,40,35,Low,Low,Low,Low,26,25,38,35
2693,2694,36103170201,2015,1,35620,"New York-Newark-Jersey City, NY-NJ-PA Metro Area",36103,36,NY,1150,...,62,61,Low,High,Moderate,Moderate,40,77,59,56
2694,2695,36103170202,2015,1,35620,"New York-Newark-Jersey City, NY-NJ-PA Metro Area",36103,36,NY,419,...,50,50,Low,High,Moderate,Moderate,37,67,48,48
2695,2696,36103180300,2015,1,35620,"New York-Newark-Jersey City, NY-NJ-PA Metro Area",36103,36,NY,614,...,67,78,Very High,Very High,High,High,82,95,64,72
2696,2697,36103190401,2015,1,35620,"New York-Newark-Jersey City, NY-NJ-PA Metro Area",36103,36,NY,1999,...,29,24,Low,Very Low,Low,Low,22,7,28,23
2697,2698,36103190402,2015,1,35620,"New York-Newark-Jersey City, NY-NJ-PA Metro Area",36103,36,NY,558,...,55,55,Moderate,Moderate,Moderate,Moderate,41,55,53,51
2698,2699,36103190403,2015,1,35620,"New York-Newark-Jersey City, NY-NJ-PA Metro Area",36103,36,NY,731,...,61,58,Low,Moderate,Moderate,Moderate,39,50,58,54
2699,2700,36103190502,2015,1,35620,"New York-Newark-Jersey City, NY-NJ-PA Metro Area",36103,36,NY,503,...,65,66,Moderate,Moderate,High,High,59,51,62,61
2700,2701,36103190503,2015,1,35620,"New York-Newark-Jersey City, NY-NJ-PA Metro Area",36103,36,NY,666,...,98,87,Moderate,Moderate,Very High,Very High,41,54,99,82
2701,2702,36103190504,2015,1,35620,"New York-Newark-Jersey City, NY-NJ-PA Metro Area",36103,36,NY,365,...,85,82,High,High,Very High,High,68,63,84,77
2702,2703,36103190601,2015,1,35620,"New York-Newark-Jersey City, NY-NJ-PA Metro Area",36103,36,NY,1023,...,68,66,Moderate,High,High,Moderate,46,63,65,60
2703,2704,36103190603,2015,1,35620,"New York-Newark-Jersey City, NY-NJ-PA Metro Area",36103,36,NY,825,...,63,53,Low,Very Low,Moderate,Moderate,34,12,59,50
2704,2705,36103190604,2015,1,35620,"New York-Newark-Jersey City, NY-NJ-PA Metro Area",36103,36,NY,644,...,86,73,Moderate,Low,Very High,High,44,25,84,67
2705,2706,36103190704,2015,1,35620,"New York-Newark-Jersey City, NY-NJ-PA Metro Area",36103,36,NY,458,...,88,78,Moderate,Low,Very High,High,53,33,87,72
2706,2707,36103190705,2015,1,35620,"New York-Newark-Jersey City, NY-NJ-PA Metro Area",36103,36,NY,603,...,47,43,Low,Low,Moderate,Moderate,34,23,45,42
2707,2708,36103190706,2015,1,35620,"New York-Newark-Jersey City, NY-NJ-PA Metro Area",36103,36,NY,699,...,69,65,Moderate,Moderate,High,Moderate,45,43,66,59
2708,2709,36103190707,2015,1,35620,"New York-Newark-Jersey City, NY-NJ-PA Metro Area",36103,36,NY,1104,...,94,90,High,High,Very High,Very High,66,79,94,86
2709,2710,36103190708,2015,1,35620,"New York-Newark-Jersey City, NY-NJ-PA Metro Area",36103,36,NY,381,...,85,83,High,Very High,Very High,High,64,83,84,78
2710,2711,36103190800,2015,1,35620,"New York-Newark-Jersey City, NY-NJ-PA Metro Area",36103,36,NY,498,...,72,72,Moderate,Very High,High,High,53,81,69,66
2711,2712,36103200901,2015,1,35620,"New York-Newark-Jersey City, NY-NJ-PA Metro Area",36103,36,NY,106,...,61,64,Moderate,Moderate,Moderate,Moderate,58,58,58,58
2712,2713,36103200902,2015,1,35620,"New York-Newark-Jersey City, NY-NJ-PA Metro Area",36103,36,NY,881,...,76,76,Moderate,Very High,High,High,53,95,74,70
2713,2714,36103201001,2015,1,35620,"New York-Newark-Jersey City, NY-NJ-PA Metro Area",36103,36,NY,1600,...,72,72,High,Moderate,High,High,65,49,69,66
2714,2715,36103201003,2015,1,35620,"New York-Newark-Jersey City, NY-NJ-PA Metro Area",36103,36,NY,636,...,89,80,Moderate,Moderate,Very High,High,51,58,89,74
2715,2716,36103201004,2015,1,35620,"New York-Newark-Jersey City, NY-NJ-PA Metro Area",36103,36,NY,382,...,97,94,Very High,Moderate,Very High,Very High,83,56,97,93
2716,2717,36103201100,2015,1,35620,"New York-Newark-Jersey City, NY-NJ-PA Metro Area",36103,36,NY,1783,...,55,43,Very Low,Moderate,Moderate,Moderate,8,48,53,41

In [11]:
df_income_S = pd.read_csv("Income by Location 2.csv")

In [12]:
df_income_S = df_income_S[df_income_S.Year == 2015]

In [13]:
df_income_S['ID'] = df_income_S['ID Geography'].str.extract(r"US(.*)")

In [14]:
df_income_S

,ID Year,Year,ID Race,Race,Household Income by Race,Household Income by Race Moe,Geography,ID Geography,ID
644,2015,2015,0,Total,94492,26938.0,"Census Tract 1803, Suffolk County, NY",14000US36103180300,36103180300
645,2015,2015,0,Total,202292,34700.0,"Census Tract 1101.01, Suffolk County, NY",14000US36103110101,36103110101
646,2015,2015,0,Total,103828,11483.0,"Census Tract 1470.03, Suffolk County, NY",14000US36103147003,36103147003
647,2015,2015,0,Total,106354,16006.0,"Census Tract 1246.01, Suffolk County, NY",14000US36103124601,36103124601
648,2015,2015,0,Total,123214,29181.0,"Census Tract 1122.10, Suffolk County, NY",14000US36103112210,36103112210
649,2015,2015,0,Total,87976,9173.0,"Census Tract 1458.04, Suffolk County, NY",14000US36103145804,36103145804
650,2015,2015,0,Total,123125,34895.0,"Census Tract 1470.04, Suffolk County, NY",14000US36103147004,36103147004
651,2015,2015,0,Total,64250,17258.0,"Census Tract 1238.02, Suffolk County, NY",14000US36103123802,36103123802
652,2015,2015,0,Total,80182,32751.0,"Census Tract 1907.05, Suffolk County, NY",14000US36103190705,36103190705
653,2015,2015,0,Total,86176,9582.0,"Census Tract 1594.11, Suffolk County, NY",14000US36103159411,36103159411
654,2015,2015,0,Total,122692,15953.0,"Census Tract 1471, Suffolk County, NY",14000US36103147100,36103147100
655,2015,2015,0,Total,79219,13795.0,"Census Tract 1229.02, Suffolk County, NY",14000US36103122902,36103122902
656,2015,2015,0,Total,110417,15784.0,"Census Tract 1697.01, Suffolk County, NY",14000US36103169701,36103169701
657,2015,2015,0,Total,54707,13198.0,"Census Tract 1472, Suffolk County, NY",14000US36103147200,36103147200
658,2015,2015,0,Total,84486,17627.0,"Census Tract 1458.05, Suffolk County, NY",14000US36103145805,36103145805
659,2015,2015,0,Total,129844,24006.0,"Census Tract 1122.06, Suffolk County, NY",14000US36103112206,36103112206
660,2015,2015,0,Total,59771,12069.0,"Census Tract 1234.02, Suffolk County, NY",14000US36103123402,36103123402
661,2015,2015,0,Total,65246,8936.0,"Census Tract 1473, Suffolk County, NY",14000US36103147300,36103147300
662,2015,2015,0,Total,122917,10328.0,"Census Tract 1351.04, Suffolk County, NY",14000US36103135104,36103135104
663,2015,2015,0,Total,95158,7405.0,"Census Tract 1458.07, Suffolk County, NY",14000US36103145807,36103145807
664,2015,2015,0,Total,71038,7921.0,"Census Tract 1243, Suffolk County, NY",14000US36103124300,36103124300
665,2015,2015,0,Total,81346,7857.0,"Census Tract 1474.01, Suffolk County, NY",14000US36103147401,36103147401
666,2015,2015,0,Total,78173,15781.0,"Census Tract 1229.01, Suffolk County, NY",14000US36103122901,36103122901
667,2015,2015,0,Total,122151,7386.0,"Census Tract 1122.04, Suffolk County, NY",14000US36103112204,36103112204
668,2015,2015,0,Total,110500,18050.0,"Census Tract 1594.10, Suffolk County, NY",14000US36103159410,36103159410
669,2015,2015,0,Total,141477,32994.0,"Census Tract 1474.02, Suffolk County, NY",14000US36103147402,36103147402
670,2015,2015,0,Total,66042,23886.0,"Census Tract 1904.03, Suffolk County, NY",14000US36103190403,36103190403
671,2015,2015,0,Total,76379,12216.0,"Census Tract 1458.08, Suffolk County, NY",14000US36103145808,36103145808
672,2015,2015,0,Total,113115,17523.0,"Census Tract 1475.01, Suffolk County, NY",14000US36103147501,36103147501
673,2015,2015,0,Total,130057,7893.0,"Census Tract 1349.03, Suffolk County, NY",14000US36103134903,36103134903
...,...,...,...,...,...,...,...,...,...
936,2015,2015,0,Total,130455,27193.0,"Census Tract 1122.13, Suffolk County, NY",14000US36103112213,36103112213
937,2015,2015,0,Total,158646,26170.0,"Census Tract 1104.01, Suffolk County, NY",14000US36103110401,36103110401
938,2015,2015,0,Total,104118,19274.0,"Census Tract 1588.03, Suffolk County, NY",14000US36103158803,36103158803
939,2015,2015,0,Total,67156,6158.0,"Census Tract 1587.04, Suffolk County, NY",14000US36103158704,36103158704
940,2015,2015,0,Total,80375,18451.0,"Census Tract 1700.01, Suffolk County, NY",14000US36103170001,36103170001
941,2015,2015,0,Total,108682,14309.0,"Census Tract 1468, Suffolk County, NY",14000US36103146800,36103146800
942,2015,2015,0,Total,71447,17417.0,"Census Tract 1587.05, Suffolk County, NY",14000US36103158705,36103158705
943,2015,2015,0,Total,83015,5907.0,"Census Tract 1230.01, Suffolk County, NY",14000US36103123001,36103123001
944,2015,2015,0,Total,120726,10183.0,"Census Tract 1103, Suffolk County, NY",14000US36103110300,36103110300
945,2015,2015,0,Total,69328,8726.0,"Census Tract 1457.04, Suffolk County, NY",14000US36103145704,36103145704
946,2015,2015,0,Total,91063,13463.0,"Census Tract 1587.07, Suffolk County, NY",14000US36103158707,36103158707
947,2015,2015,0,Total,125357,16611.0,"Census Tract 1351.02, Suffolk County, NY",14000US36103135102,36103135102
948,2015,2015,0,Total,99655,18876.0,"Census Tract 1102, Suffolk County, NY",14000US36103110200,36103110200
949,2015,2015,0,Total,101740,15554.0,"Census Tract 1469.01, Suffolk County, NY",14000US36103146901,36103146901
950,2015,2015,0,Total,54722,15626.0,"Census Tract 1587.08, Suffolk County, NY",14000US36103158708,36103158708
951,2015,2015,0,Total,114286,25342.0,"Census Tract 1349.02, Suffolk County, NY",14000US36103134902,36103134902
952,2015,2015,0,Total,72467,9421.0,"Census Tract 2011, Suffolk County, NY",14000US36103201100,36103201100
953,2015,2015,0,Total,108704,22688.0,"Census Tract 1588.02, Suffolk County, NY",14000US36103158802,36103158802
954,2015,2015,0,Total,82083,16035.0,"Census Tract 1587.09, Suffolk County, NY",14000US36103158709,36103158709
955,2015,2015,0,Total,175313,22791.0,"Census Tract 1122.12, Suffolk County, NY",14000US36103112212,36103112212
956,2015,2015,0,Total,83270,16541.0,"Census Tract 1594.12, Suffolk County, NY",14000US36103159412,36103159412
957,2015,2015,0,Total,86731,17339.0,"Census Tract 1587.10, Suffolk County, NY",14000US36103158710,36103158710
958,2015,2015,0,Total,139922,22509.0,"Census Tract 1469.02, Suffolk County, NY",14000US36103146902,36103146902
959,2015,2015,0,Total,157143,27753.0,"Census Tract 1101.02, Suffolk County, NY",14000US36103110102,36103110102
960,2015,2015,0,Total,70691,16044.0,"Census Tract 1235, Suffolk County, NY",14000US36103123500,36103123500
961,2015,2015,0,Total,74331,17673.0,"Census Tract 1587.11, Suffolk County, NY",14000US36103158711,36103158711
962,2015,2015,0,Total,97583,13248.0,"Census Tract 1458.03, Suffolk County, NY",14000US36103145803,36103145803
963,2015,2015,0,Total,117188,12745.0,"Census Tract 1470.01, Suffolk County, NY",14000US36103147001,36103147001
964,2015,2015,0,Total,139306,17268.0,"Census Tract 1351.03, Suffolk County, NY",14000US36103135103,36103135103
965,2015,2015,0,Total,155125,14261.0,"Census Tract 1122.11, Suffolk County, NY",14000US36103112211,36103112211

In [15]:
df_income_N = pd.read_csv("Income by Location 3.csv")

In [16]:
df_income_N = df_income_N[df_income_N.Year == 2015]

In [17]:
df_income_N['ID'] = df_income_N['ID Geography'].str.extract(r"US(.*)")

In [18]:
df_income_N

,ID Year,Year,ID Race,Race,Household Income by Race,Household Income by Race Moe,Geography,ID Geography,ID
552,2015,2015,0,Total,111319,24017.0,"Census Tract 4062.02, Nassau County, NY",14000US36059406202,36059406202
553,2015,2015,0,Total,58092,17038.0,"Census Tract 4124, Nassau County, NY",14000US36059412400,36059412400
554,2015,2015,0,Total,95282,9075.0,"Census Tract 5195, Nassau County, NY",14000US36059519500,36059519500
555,2015,2015,0,Total,70761,14579.0,"Census Tract 4123.01, Nassau County, NY",14000US36059412301,36059412301
556,2015,2015,0,Total,142717,8718.0,"Census Tract 4125, Nassau County, NY",14000US36059412500,36059412500
557,2015,2015,0,Total,94809,7564.0,"Census Tract 4122, Nassau County, NY",14000US36059412200,36059412200
558,2015,2015,0,Total,89219,12122.0,"Census Tract 4121, Nassau County, NY",14000US36059412100,36059412100
559,2015,2015,0,Total,82148,18784.0,"Census Tract 4120, Nassau County, NY",14000US36059412000,36059412000
560,2015,2015,0,Total,201250,33744.0,"Census Tract 4126, Nassau County, NY",14000US36059412600,36059412600
561,2015,2015,0,Total,113750,20705.0,"Census Tract 5196.01, Nassau County, NY",14000US36059519601,36059519601
562,2015,2015,0,Total,100478,9172.0,"Census Tract 4119.02, Nassau County, NY",14000US36059411902,36059411902
563,2015,2015,0,Total,92917,14599.0,"Census Tract 5194, Nassau County, NY",14000US36059519400,36059519400
564,2015,2015,0,Total,151573,21145.0,"Census Tract 4127, Nassau County, NY",14000US36059412700,36059412700
565,2015,2015,0,Total,61702,5915.0,"Census Tract 4119.01, Nassau County, NY",14000US36059411901,36059411901
566,2015,2015,0,Total,94797,19816.0,"Census Tract 4118, Nassau County, NY",14000US36059411800,36059411800
567,2015,2015,0,Total,112250,30930.0,"Census Tract 4128, Nassau County, NY",14000US36059412800,36059412800
568,2015,2015,0,Total,106235,11730.0,"Census Tract 4117, Nassau County, NY",14000US36059411700,36059411700
569,2015,2015,0,Total,151761,10209.0,"Census Tract 5196.02, Nassau County, NY",14000US36059519602,36059519602
570,2015,2015,0,Total,140391,43392.0,"Census Tract 4116, Nassau County, NY",14000US36059411600,36059411600
571,2015,2015,0,Total,94054,5816.0,"Census Tract 4129, Nassau County, NY",14000US36059412900,36059412900
572,2015,2015,0,Total,198750,19853.0,"Census Tract 4115, Nassau County, NY",14000US36059411500,36059411500
573,2015,2015,0,Total,111528,26331.0,"Census Tract 4114, Nassau County, NY",14000US36059411400,36059411400
574,2015,2015,0,Total,135156,21023.0,"Census Tract 4113.02, Nassau County, NY",14000US36059411302,36059411302
575,2015,2015,0,Total,72599,12288.0,"Census Tract 4130.01, Nassau County, NY",14000US36059413001,36059413001
576,2015,2015,0,Total,107567,8165.0,"Census Tract 5197.02, Nassau County, NY",14000US36059519702,36059519702
577,2015,2015,0,Total,114567,28223.0,"Census Tract 4113.01, Nassau County, NY",14000US36059411301,36059411301
578,2015,2015,0,Total,75845,10758.0,"Census Tract 5193, Nassau County, NY",14000US36059519300,36059519300
579,2015,2015,0,Total,95148,10655.0,"Census Tract 4130.02, Nassau County, NY",14000US36059413002,36059413002
580,2015,2015,0,Total,88913,13875.0,"Census Tract 4112, Nassau County, NY",14000US36059411200,36059411200
581,2015,2015,0,Total,47974,11363.0,"Census Tract 4111, Nassau County, NY",14000US36059411100,36059411100
...,...,...,...,...,...,...,...,...,...
798,2015,2015,0,Total,208424,52887.0,"Census Tract 3016, Nassau County, NY",14000US36059301600,36059301600
799,2015,2015,0,Total,216563,25356.0,"Census Tract 3015, Nassau County, NY",14000US36059301500,36059301500
800,2015,2015,0,Total,124550,17807.0,"Census Tract 5175, Nassau County, NY",14000US36059517500,36059517500
801,2015,2015,0,Total,113073,17169.0,"Census Tract 5218.02, Nassau County, NY",14000US36059521802,36059521802
802,2015,2015,0,Total,136042,23321.0,"Census Tract 3014, Nassau County, NY",14000US36059301400,36059301400
803,2015,2015,0,Total,134309,16385.0,"Census Tract 5181, Nassau County, NY",14000US36059518100,36059518100
804,2015,2015,0,Total,108333,19671.0,"Census Tract 5176, Nassau County, NY",14000US36059517600,36059517600
805,2015,2015,0,Total,80718,18305.0,"Census Tract 3013, Nassau County, NY",14000US36059301300,36059301300
806,2015,2015,0,Total,126563,19061.0,"Census Tract 3012, Nassau County, NY",14000US36059301200,36059301200
807,2015,2015,0,Total,220208,19195.0,"Census Tract 5177.01, Nassau County, NY",14000US36059517701,36059517701
808,2015,2015,0,Total,106196,22201.0,"Census Tract 3011.02, Nassau County, NY",14000US36059301102,36059301102
809,2015,2015,0,Total,125313,20719.0,"Census Tract 5219.02, Nassau County, NY",14000US36059521902,36059521902
810,2015,2015,0,Total,83253,15406.0,"Census Tract 3011.01, Nassau County, NY",14000US36059301101,36059301101
811,2015,2015,0,Total,225208,46693.0,"Census Tract 5177.05, Nassau County, NY",14000US36059517705,36059517705
812,2015,2015,0,Total,151759,15609.0,"Census Tract 3010, Nassau County, NY",14000US36059301000,36059301000
813,2015,2015,0,Total,134856,28559.0,"Census Tract 3009, Nassau County, NY",14000US36059300900,36059300900
814,2015,2015,0,Total,105078,16018.0,"Census Tract 3008, Nassau County, NY",14000US36059300800,36059300800
815,2015,2015,0,Total,143000,16608.0,"Census Tract 5178.01, Nassau County, NY",14000US36059517801,36059517801
816,2015,2015,0,Total,75501,6392.0,"Census Tract 5220, Nassau County, NY",14000US36059522000,36059522000
817,2015,2015,0,Total,67128,18512.0,"Census Tract 3007, Nassau County, NY",14000US36059300700,36059300700
818,2015,2015,0,Total,91453,4665.0,"Census Tract 5180, Nassau County, NY",14000US36059518000,36059518000
819,2015,2015,0,Total,85536,15359.0,"Census Tract 5178.02, Nassau County, NY",14000US36059517802,36059517802
820,2015,2015,0,Total,122083,15319.0,"Census Tract 3006, Nassau County, NY",14000US36059300600,36059300600
821,2015,2015,0,Total,117361,17303.0,"Census Tract 3005, Nassau County, NY",14000US36059300500,36059300500
822,2015,2015,0,Total,106136,23637.0,"Census Tract 5179.01, Nassau County, NY",14000US36059517901,36059517901
823,2015,2015,0,Total,98487,13087.0,"Census Tract 3004, Nassau County, NY",14000US36059300400,36059300400
824,2015,2015,0,Total,124592,8178.0,"Census Tract 5227, Nassau County, NY",14000US36059522700,36059522700
825,2015,2015,0,Total,76042,9387.0,"Census Tract 3003, Nassau County, NY",14000US36059300300,36059300300
826,2015,2015,0,Total,102074,12487.0,"Census Tract 5179.02, Nassau County, NY",14000US36059517902,36059517902
827,2015,2015,0,Total,95172,12930.0,"Census Tract 4090, Nassau County, NY",14000US36059409000,36059409000

In [19]:
df_income_LI = pd.concat([df_income_N, df_income_S])

In [20]:
df_income_LI['Region'] = 'LI'

In [24]:
df_child.c5_COI_met.value_counts()

Low          671
Moderate     642
Very Low     575
High         487
Very High    342
Name: c5_COI_met, dtype: int64

In [25]:
df_income_LI['ID'] = df_income_LI['ID'].astype(int)

In [26]:
df = pd.merge(df_child,df_income_metro,left_on='geoid',right_on='ID')

In [27]:
df.to_csv("income-child-LI.csv",index=False)